name: check

on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Rollbar
      uses: rollbar/github-deploy-action@2.1.1
      with:
        environment: 'production'
        version: 'f831cb0bd14ab3bf0c30f572a0e8c03ee3e44e16'
        status: 'succeeded'
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        ROLLBAR_USERNAME: 'shalin.anton8'
