name: check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linter
        run: |
          poetry run flake8 task_manager
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE_ENV }}
        with:
          coverageCommand: make test
          debug: true
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Rollbar
      uses: rollbar/github-deploy-action@2.1.1
      with:
        environment: 'production'
        version: 'f831cb0bd14ab3bf0c30f572a0e8c03ee3e44e16'
        status: 'succeeded'
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        ROLLBAR_USERNAME: 'shalin.anton8'
